name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: windows-latest
    steps:
      - name: Print to console
        run: echo hello
      - name: Print a few lines
        run: |
          echo 1 line
          echo 2 line


